# -*- coding: utf-8 -*-
"""Airline.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O76mkXSfDwDtustLX4Z9jL-kLVTSG0wT
"""

import pandas as pd
import matplotlib.pyplot as plt

# Import the dataset
data = pd.read_csv("/content/Airline Dataset Updated.csv")

# Display the first 5 rows
print(data.head())

# Optionally: Display some basic statistics or visualize the data
data.describe()