# -*- coding: utf-8 -*-
"""World Energy Consumption.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rScRgn2HmoL46ZQjYAWnmg1BmTtr4m68
"""

import pandas as pd
import matplotlib.pyplot as plt

# Import the dataset
data = pd.read_csv("/content/World Energy Consumption.csv")

# Display the first 5 rows
print(data.head())

# Optionally: Display some basic statistics or visualize the data
data.describe()